[general]
import = [
"alacritty=theme/themes/gruvbox_dark.toml"
]
live_config_reload = true

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Windowed"
dynamic_padding = true
padding.x = 10
padding.y = 10
blur = true
dimensions = { columns = 0, lines = 0 }

[font]
size = 16

[cursor]
style = { shape = "block", blinking = "Always" }
blink_timeout = 0
